name: flutter_auth_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  flutter_riverpod: ^2.3.10
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  image_picker: ^1.0.4
  uuid: ^4.2.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
